# -*- coding: utf-8 -*-
"""Copy of Data Analytics_XX.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-VMEeBypx16HSAcpK4RGv6dBRpc4ijhG

# **Final Test: Practical**
Follow the instruction given in the codes cells to perform the respective data analytics processes using the titanic dataset provided.
NB: REPLACE THE XX IN THE FILE WITH YOUR FULL DETAILS
"""

#[20/40]
#Load the required libraries/modules [2]
import pandas as pd
import numpy as np

#Import data from the CSV file provided into a DF[2]
df = pd.read_csv("titanic.csv")

#display the top 10 records [2]
df.head(10)

#display the bottom 10 records [2]
df.tail(10)

#Provide a basic summary of df information[2]
df.dtypes

#Provide a descriptive statistical summary of df information[2]
df.describe()

#Find null values in the whole df[2]
df.isnull()

#Replace all the missing/null vales in the age column with the mean of all ages [2]
Age = df['Age']
Age.describe()

mean = Age.mean()
print(f"Mean ={mean}")

df.fill(value=29.69911764705882
,subset=["Age"]).show()

#drop the cabin column from the df [2]
df.pop("Cabin")

#create a box plot of the Fares column in the df(What is your interpretation?)[4]
#[-4]

#create a histogram of the Ages column(What is your interpretation?)[5]
#[-5]

#Using a scatter plot, illustrate any relation between age and survived(What is your interpretation?)[5]
#[-5]

#Using  a bar plot ilustrated the survival rate of passenger per gender(What is your conclustions from this infomation?) [6]
#[-6]