# -*- coding: utf-8 -*-
"""Class exercise 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RfLhCxrVMMtFQeA6UnEiJo4_P-0hV0aQ

Q1, Create a sample assertion block to ensure the user has not provided an empty input
"""

num1 = int(input("Enter the first number:"))
num2 = int(input("Enter the second number:"))

assert( num1%2==0 and num2%2== 0),"This input is empty/ provide even number."
print("The numbers %d and %d are all even."%(num1,num2))

"""Q2, Create 2 custom exceptions, one for Gender and another Age"""

class GenderError(Exception):
  def __init__(self, Gender, message = "Person not male"):
    self.gender = Gender
    self.message = message
    super().__init__(self.message)

  def __str__(self) -> str:
    return f'{self.gender} -> {self.message}'
    Gender = str("Are you male or female ??")
    raise GenderError(Gender)

class AgeError(Exception):  #calculating the year of birth from the age

 try:
    age= -10
    print("Age is:")
    print(age)
    if age<0:
        raise AgeError
    yearOfBirth= 2022-age
    print("Year of Birth is:")
    print(yearOfBirth)
 except AgeError:
    print("Input Correct age.")

"""Q3, Create a person class and raise the exceptions above"""

class Person:
  def __init__(self, name, age):
    self.name = name                      # person class
    self.age = age

p1 = Person("John", 10)

print(p1.name)
print(p1.age)

class AgeError(Exception)

try:
    age= 10
    print("Age is:")                       #AgeError exception
    print(age)
    if age<0:
        raise AgeError
    yearOfBirth= 2021-age
    print("Year of Birth is:")
    print(yearOfBirth)
except AgeError:
    print("Input Correct age.")

#5. Replace all the _____________ with a correct expections in Python
print (" Learning Exceptions...")
try:
 num1= int(input ("Enter the first number"))
 num2=int(input("Enter the second number"))
 quotient=(num1/num2)
 print ("Both the numbers entered were correct")
except _____________: # to enter only integers
 print (" Please enter only numbers")
except ____________: # Denominator should not be zero
 print(" Number 2 should not be zero")
else:
 print(" Great .. you are a good programmer")
___________: # to be executed at the end
 print(" JOB OVER... GO GET SOME REST")

ValueError
ZeroDivisionError
finally

