# -*- coding: utf-8 -*-
"""Pandas Ex 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cm2T1ixI8-frtNhLWOTJFb0TJEmbMVMz

Q1, Write a Pandas program to create and display a one-dimensional array-like object containing an
array of data.
"""

import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print(ds)

"""Q2, Write a Pandas program to convert a Panda module Series to Python list. Display the list and it’s
type.
"""

import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(ds)
print(type(ds))
print("Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))

"""Q3, Write a Python program to add, subtract, multiple and divide two Pandas Series."""

import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Addition:")
print(ds)
print("Subtraction:")
ds = ds1 - ds2
print(ds)
print("Multiplication:")
ds = ds1 * ds2
print(ds)
print("Division:")
ds = ds1 / ds2
print(ds)

"""Q4, Write a Python program to get the largest integer smaller or equal to the division of the inputs."""

import numpy as np
x = [1., 2., 3., 4.]

print(x)

print(np.floor_divide(x, 1.5))

"""Q5, Write a Python program to convert a dictionary to a Pandas series.
Sample Series:
Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a 100
b 200
c 300
d 400
e 800
dtype: int64
"""

import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}

print(d1)
new_series = pd.Series(d1)

print(new_series)

"""Q6, Write a Pandas program to convert a NumPy array to a Pandas series."""

import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

"""Q7, Write a Pandas program to change the data type of given a column or a Series."""

import pandas as pd
s1 = pd.Series(['100', '200', 'Andrew', '300.12', 'Bob'])

print(s1)

print("Changed to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)

"""Q8, Write a Pandas program to convert a given Series to an array."""

import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', 'Andrew', '300.12', 'Bob'])

print(s1)

a = np.array(s1.values.tolist())
print (a)

"""Q9, Write a Pandas program to sort a given Series."""

import pandas as pd
s = pd.Series(['100', '200', 'Andrew', '300.12', 'Bob'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)

"""Q10,Write a Pandas program to add some data to an existing Series."""

import pandas as pd
s = pd.Series(['100', '200', 'Andrew', '300.12', 'Bob'])

print(s)


new_s = s.append(pd.Series(['400', 'Lee']))
print(new_s)